-- Actualización: Ordenes de Proceso (OP)

ALTER TABLE fruta_proceso
    ADD COLUMN ID_OPROCESO INT NULL AFTER ID_TPROCESO;

CREATE TABLE IF NOT EXISTS exportadora_oproceso (
    ID_OPROCESO INT NOT NULL AUTO_INCREMENT,
    NUMERO_OPROCESO VARCHAR(100) NOT NULL,
    FECHA_TERMINO_ESTIMADA DATE NULL,
    CANTIDAD_CAJA INT NULL,
    OBSERVACION_OPROCESO VARCHAR(500) NULL,
    ID_EMPRESA INT NOT NULL,
    ID_USUARIOI INT NULL,
    ID_USUARIOM INT NULL,
    INGRESO DATETIME NULL,
    MODIFICACION DATETIME NULL,
    ESTADO_REGISTRO TINYINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_OPROCESO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS exportadora_oproceso_mercado (
    ID_OPROCESO_MERCADO INT NOT NULL AUTO_INCREMENT,
    ID_OPROCESO INT NOT NULL,
    ID_MERCADO INT NOT NULL,
    PRIMARY KEY (ID_OPROCESO_MERCADO),
    UNIQUE KEY uk_op_mercado (ID_OPROCESO, ID_MERCADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS exportadora_oproceso_productor_variedad (
    ID_OPROCESO_PRODUCTOR_VARIEDAD INT NOT NULL AUTO_INCREMENT,
    ID_OPROCESO INT NOT NULL,
    ID_PRODUCTOR INT NOT NULL,
    ID_VESPECIES INT NOT NULL,
    PRIMARY KEY (ID_OPROCESO_PRODUCTOR_VARIEDAD),
    UNIQUE KEY uk_op_productor_variedad (ID_OPROCESO, ID_PRODUCTOR, ID_VESPECIES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS exportadora_oproceso_estandar (
    ID_OPROCESO_ESTANDAR INT NOT NULL AUTO_INCREMENT,
    ID_OPROCESO INT NOT NULL,
    ID_ESTANDAR INT NOT NULL,
    PRIMARY KEY (ID_OPROCESO_ESTANDAR),
    UNIQUE KEY uk_op_estandar (ID_OPROCESO, ID_ESTANDAR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE fruta_proceso
    ADD CONSTRAINT fk_fruta_proceso_oproceso
    FOREIGN KEY (ID_OPROCESO) REFERENCES exportadora_oproceso (ID_OPROCESO)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE exportadora_oproceso_mercado
    ADD CONSTRAINT fk_opmercado_op FOREIGN KEY (ID_OPROCESO) REFERENCES exportadora_oproceso (ID_OPROCESO)
    ON UPDATE CASCADE ON DELETE CASCADE,
    ADD CONSTRAINT fk_opmercado_mercado FOREIGN KEY (ID_MERCADO) REFERENCES fruta_mercado (ID_MERCADO)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE exportadora_oproceso_productor_variedad
    ADD CONSTRAINT fk_opprodvar_op FOREIGN KEY (ID_OPROCESO) REFERENCES exportadora_oproceso (ID_OPROCESO)
    ON UPDATE CASCADE ON DELETE CASCADE,
    ADD CONSTRAINT fk_opprodvar_productor FOREIGN KEY (ID_PRODUCTOR) REFERENCES fruta_productor (ID_PRODUCTOR)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    ADD CONSTRAINT fk_opprodvar_variedad FOREIGN KEY (ID_VESPECIES) REFERENCES fruta_vespecies (ID_VESPECIES)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE exportadora_oproceso_estandar
    ADD CONSTRAINT fk_opestandar_op FOREIGN KEY (ID_OPROCESO) REFERENCES exportadora_oproceso (ID_OPROCESO)
    ON UPDATE CASCADE ON DELETE CASCADE,
    ADD CONSTRAINT fk_opestandar_estandar FOREIGN KEY (ID_ESTANDAR) REFERENCES estandar_eexportacion (ID_ESTANDAR)
    ON UPDATE CASCADE ON DELETE RESTRICT;
